# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.12-slim

# Set working directory
WORKDIR /app

# Copy project files
COPY . .

# Install dependencies
RUN pip install . --no-cache-dir

# Ensure Python output is unbuffered
ENV PYTHONUNBUFFERED=1

# Use the CLI entrypoint provided by the package
ENTRYPOINT ["overseerr-mcp"]
